[build]
  command = "npm run build"
  publish = "dist"

[dev]
  command = "npm run dev"
  port = 3092
  autoLaunch = false

# Proxy API and OAuth requests to the production backend
[[redirects]]
  from = "/api/*"
  to = "https://www.sigmacode.ai/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/oauth/*"
  to = "https://www.sigmacode.ai/oauth/:splat"
  status = 200
  force = true

# Single Page App redirect so client-side routing works
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Optional: set some sensible cache headers for static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
