name: CI (Next.js - sigmacode_ai)

on:
  push:
    branches: [ master, main ]
    paths:
      - 'sigmacode_ai/**'
      - '.github/workflows/ci.yml'
  pull_request:
    branches: [ master, main ]
    paths:
      - 'sigmacode_ai/**'
      - '.github/workflows/ci.yml'

permissions:
  contents: read

jobs:
  build:
    name: Lint • Typecheck • Test • Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: sigmacode_ai

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'pnpm'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint
        run: |
          if [ -f package.json ] && jq -e '.scripts.lint' package.json > /dev/null; then
            pnpm lint
          else
            echo "No lint script; skipping"
          fi

      - name: Typecheck
        run: |
          if [ -f package.json ] && jq -e '.scripts["type-check"] // .scripts.typecheck' package.json > /dev/null; then
            (pnpm run type-check || pnpm run typecheck)
          else
            echo "No typecheck script; skipping"
          fi

      - name: Test
        run: |
          if [ -f package.json ] && jq -e '.scripts.test' package.json > /dev/null; then
            pnpm test -- --ci --reporters=default --reporters=jest-junit || true
          else
            echo "No test script; skipping"
          fi

      - name: Build (client CI)
        run: pnpm run frontend:ci
